---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file_bck }}"
        dest: "{{ frr_ospf_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ frr_ospf_conf_file_bck }}"
        state: absent

    - name: Restore backup of /etc/network/interfaces
      copy:
        src: /etc/network/interfaces.bck
        dest: /etc/network/interfaces
        remote_src: true

    - name: Remove backup file
      file:
        path: /etc/network/interfaces.bck
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart frr
      service:
        name: frr
        state: restarted

    - command: "goes restart"
