---

# Uninstall packages stack
- include: playbooks/installation/uninstall_packages.yml


# Install quagga
- include: playbooks/installation/quagga_install.yml


# Restart goes
- include: playbooks/goes_restart.yml


# Run all docker containerized test cases
- include: playbooks/docker/quagga_ospf_traffic.yml

#- include: playbooks/docker/quagga_ospf_traffic_subports.yml

- include: playbooks/docker/quagga_ospf_traffic_vlan.yml
