---

# Uninstall packages stack
- include: playbooks/installation/uninstall_packages.yml


# Upgrade invaders to latest goes from /home/mpleso/platinabot
#- include: playbooks/upgrade_invaders_to_latest_goes.yml


# Reset invaders to default state
#- include: playbooks/reset_invaders_to_default.yml


# Reset invaders to default state
- include: playbooks/master_reset_invaders.yml


# Install quagga
- include: playbooks/installation/quagga_install.yml


# Restart goes
- include: playbooks/goes_restart.yml


# Run few quagga bgp test cases
- include: playbooks/bgp/quagga_bgp_peering_ebgp.yml

- include: playbooks/bgp/quagga_bgp_peering_ibgp_loopback.yml

- include: playbooks/bgp/quagga_bgp_peering_weight.yml

- include: playbooks/bgp/quagga_bgp_peering_if_down.yml

- include: playbooks/bgp/quagga_bgp_peering_route_reflector.yml

- include: playbooks/bgp/quagga_bgp_traffic_test.yml


# Run few quagga ospf test cases
- include: playbooks/ospf/quagga_ospf_basic.yml

- include: playbooks/ospf/quagga_ospf_loopback.yml

- include: playbooks/ospf/quagga_ospf_administrative_distance.yml


# Run all quagga isis test cases
- include: playbooks/isis/quagga_isis_basic.yml

- include: playbooks/isis/quagga_isis_neighbors.yml


# Uninstall packages stack
- include: playbooks/installation/uninstall_packages.yml


# Restart goes
- include: playbooks/goes_restart.yml


# Run few port provisioning test cases
#- include: playbooks/port_provision/100g_cr_fec_cl91_autoneg_off.yml

#- include: playbooks/port_provision/10g_cr_fec_none_autoneg_on_lanes_1_count_4.yml

#- include: playbooks/port_provision/25g_cr_fec_none_autoneg_off.yml

#- include: playbooks/port_provision/40g_cr_fec_cl74_autoneg_off_lanes_2_count_2.yml

#- include: playbooks/port_provision/40g_cr_fec_cl74_autoneg_on_lanes_4_count_1.yml

#- include: playbooks/port_provision/40g_cr_fec_none_autoneg_off_lanes_2_count_2.yml

#- include: playbooks/port_provision/40g_cr_fec_none_autoneg_on_lanes_4_count_1.yml

#- include: playbooks/port_provision/50g_cr_fec_cl74_autoneg_off_lanes_2_count_2.yml

#- include: playbooks/port_provision/50g_cr_fec_none_autoneg_off_lanes_2_count_2.yml
