---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Delete any existing namespaces
      command: ip -all netns del

    - name: Stop any existing iperf sessions
      command: pkill iperf

    - name: Stop and remove any existing docker containers
      shell: "{{ item }}"
      with_items:
      - "docker stop $(docker ps -a -q)"
      - "docker rm $(docker ps -a -q)"

    - name: Copy default network interfaces file
      copy:
        src: "../../../files/{{inventory_hostname}}/network_interfaces_master"
        dest: "{{ network_interfaces_file }}"

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes stop'
      - 'rmmod platina-mk1'
      - 'modprobe platina-mk1'
      - 'ifdown -a --allow vnet'
      - 'ifup -a'
      - 'goes start'
