---

- hosts: leaf[0]:spine[0]
  become: true
  ignore_errors: yes
  tasks:
    - name: Stop iperf server instances
      command: "pkill iperf"

    - shell: "rm ~/iperf-parallel-servers.sh"

    - name: Restore backup of /etc/goes/start
      copy:
        src: "{{ goes_start_file_bck }}"
        dest: "{{ goes_start_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ goes_start_file_bck }}"
        state: absent

    - name: Remove portprovision file
      file:
        path: /etc/goes/portprovision
        state: absent

    - command: "goes restart"
