---

- hosts: leaf[0]:spine[0]
  become: true
  ignore_errors: yes
  tasks:
    - name: Delete any existing namespaces
      command: ip -all netns del

    - name: Stop any existing iperf sessions
      command: pkill iperf

    - name: Copy default network interfaces file
      template:
        src: "../../files/{{inventory_hostname}}/network_interfaces_master"
        dest: "{{ network_interfaces_file }}"

    - name: Copy default goesd-platina-mk1-modules.conf
      template:
        src: "../../files/{{ inventory_hostname }}/goesd-platina-mk1-modules.conf_default"
        dest: "{{ goesd_modules_file }}"

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - 'modprobe platina-mk1 provision=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1'
      - 'service networking restart'
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 5
