---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/frr/isisd.conf
      copy:
        src: "{{ frr_isis_conf_file_bck }}"
        dest: "{{ frr_isis_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ frr_isis_conf_file_bck }}"
        state: absent

    - name: Update interface ip and mtu
      update_eth_ip_mtu:
        switch_name: "{{ inventory_hostname }}"
        config_file: "{{ lookup('file', '../../files/{{inventory_hostname}}/update_eth_ip_mtu') }}"
        revert: True

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restore backup of /etc/network/interfaces
      copy:
        src: /etc/network/interfaces.bck
        dest: /etc/network/interfaces
        remote_src: true

    - name: Remove backup file
      file:
        path: /etc/network/interfaces.bck
        state: absent

    - command: "goes restart"

    - name: Restart frr
      service:
        name: frr
        state: restarted
